---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - VERSION=docker
      - PLEX_CLAIM=claim-4zEWxszisjpd1cs4XNKL
    volumes:
      - /home/sbartoul/plex/config:/config
      - /home/sbartoul/plex/tvseries:/tv
      - /home/sbartoul/plex/movies:/movies
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - /home/sbartoul/plex/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - /home/sbartoul/plex/radarr:/config
      - /home/sbartoul/plex/movies:/movies #optional
      - /home/sbartoul/plex/qbittorrent-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - /home/sbartoul/plex/sonarr:/config
      - /home/sbartoul/plex/tvseries:/tv #optional
      - /home/sbartoul/plex/qbittorrent-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/sbartoul/plex/qbittorrent:/config
      - /home/sbartoul/plex/qbittorrent-downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped